# Ansible Playbook for Docker Engine
# Used by Vagrant via Ansible Provisioner
---
- name: "Docker Engine"
  become: true
  hosts: all
  # remote_user: vagrant
  # gather_facts: false

  vars:
    - ansible_python_interpreter: /usr/bin/python3

  roles:
    - { role: common, tags: common }
    - { role: docker, tags: docker }
