# Ansible Playbook for Docker Engine
# Used by Vagrant via Ansible Provisioner
---
- name: "Docker Engine"
  become: true
  hosts: all

  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - remote_user: vagrant


  roles:
    - { role: common, tags: common }
    - { role: docker, tags: docker }
